// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckDriverApp.Context;

namespace TruckDriverApp.Migrations
{
    [DbContext(typeof(TruckDriverAppDbContext))]
    [Migration("20220413100234_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("TruckDriverApp.Model.planfrieght", b =>
                {
                    b.Property<int>("plan_FrieghtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("End_Route")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Frieght_Quotation")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Start_Route")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Transport_Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("plan_FrieghtId");

                    b.ToTable("PPlanFrieght");
                });

            modelBuilder.Entity("TruckDriverApp.Model.registermodel", b =>
                {
                    b.Property<int>("Driver_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Aadhaar_no")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Authkey")
                        .HasColumnType("longtext");

                    b.Property<string>("Confirm_password")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("License_no")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile_number")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("Pincode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Village")
                        .HasColumnType("longtext");

                    b.HasKey("Driver_Id");

                    b.ToTable("rRegisterModel");
                });
#pragma warning restore 612, 618
        }
    }
}
